# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://notes-peter.baumgartner.net/"


# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-106334854-6"
# Enable comments by entering your Disqus shortname
disqusShortname = "petzi-2"

## Turn off Disqus when output is locally: blogdown:::serve_site() DOES NOT WORK!
## see https://github.com/rstudio/blogdown/issues/52#issuecomment-288407836


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

languageCode = "en-us"
DefaultContentLanguage = "en"

# pb: Disable comments on the whole site or use it in the header for just one article
# TOML: disable_comments = true
# YAML: disable_comments: true

title = "Peter on Open Science & Data Science Education"
theme = "docdock"
themesdir = "themes"

footnotereturnlinkcontents = "↩"

# for emoji use the following format: :<name of emoji>:
# for example: :wink:
# list of names at: https://github.com/afeld/emoji-css/tree/gh-pages/emoji
# list of icons: https://afeld.github.io/emoji-css/ (e.g. convert <i class="em em-anchor"></i> to :anchor:)
# see also: https://emojipedia.org/ (copy & paste)
enableEmoji = true

# relativeURLs = false # default value!
# e.g. I have to give the path but I can use slugs!

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
localSite = "https://127.0.0.1;4321"
productionSite = "https://notes.peter-baumgartner.net"
 # Prefix URL to edit current page. Will display an "Edit this page" button
 # on top right hand corner of every page.
 # Useful to give opportunity to people to create merge request for your doc.
editURL = "https://github.com/petzi53/weblog-notes/edit/master/content/"

# Author of the site, will be used in meta information
  author = "Peter Baumgartner"
# Description of the site, will be used in meta information
  description = "Open Science & Data Science Education"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

staticman = false

noHomeIcon = false # default is

summary_length = 500


# Disable search function. It will hide search bar
        noSearch = true # default is false

# Shows a checkmark for visited pages on the menu
        showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
        themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
# Order sections in menu by "weight" or "title". Default to "weight"
        ordersectionsby = "weight"

# Javascript and CSS cache are automatically busted when new version of site is generated.
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
  # disableAssetsBusting = false

# Set this to true to disable copy-to-clipboard button for inline code.
# DOES NOT WORK
  disableInlineCopyToClipBoard = true

# A title for shortcuts in menu is set by default. Set this to true to disable it.
  # disableShortcutsTitle = false

# When using mulitlingual website, disable the switch language button.
  # disableLanguageSwitchingButton = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
        pre = "<h3>More</h3>"
        name = "<i class='fa fa-envelope-o'>&nbsp;&nbsp;</i> Contact"
        url = "/contact"
        weight = 5


[[menu.shortcuts]]
        name = "<i class='fa fa-github'>&nbsp;&nbsp;</i> Github repo"
        identifier = "ds"
        url = "https://github.com/petzi53/weblog-notes/"
        weight = 10

[[menu.shortcuts]]
        name = "<i class='fa fa-bullhorn'>&nbsp;&nbsp;</i> Credits"
        url = "/credits"
        weight = 30

[[menu.shortcuts]]
        name = "<i class='fa fa-bookmark'>&nbsp;&nbsp;&nbsp;</i> Categories"
        url = "/categories/"
        weight = 40
[[menu.shortcuts]]
        name = "<i class='fa fa-tags'>&nbsp;&nbsp;</i> Tags"
        url = "/tags/"
        weight = 50
[[menu.shortcuts]]
        name = "<i class='fa fa-rss'>&nbsp;&nbsp;&nbsp;</i> Subscribe"
        url = "/index.xml"
        weight = 60


